<?php include_once("templates/header.phtml") ?>

    <main class="container mx-auto py-10">
        <h1 class="text-4xl font-bold pb-10">TODOS</h1>
        <div class="flex flex-col pb-10 ">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="text-center px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    User ID
                                </th>
                                <th scope="col" class="text-center px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    ID
                                </th>
                                <th scope="col" class="text-center px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Title
                                </th>
                                <th scope="col" class="text-center px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Completed
                                </th>
                            </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">
                            <?php foreach ($todos as $todo) : ?>
                                <tr>
                                <td class="px-6 py-4 text-center whitespace-nowrap">
                                    <?= $todo->userId?>
                                </td>
                                <td class="px-6 py-4 text-center whitespace-nowrap">
                                    <?= $todo->id?>
                                </td>
                                <td class="px-6 py-4 text-left whitespace-nowrap text-sm text-gray-500">
                                    <?= $todo->title?>
                                </td>
                                <td class="px-6 py-4 text-center whitespace-nowrap">
                                    <?php if($todo->completed) : ?>
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                          ✓
                                        </span>
                                    <?php else :?>
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-green-800">
                                          ✗
                                        </span>
                                    <?php endif; ?>
                                </td>

                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </main>

<?php include_once("templates/footer.phtml") ?>